#!/usr/bin/env node
/**
 * Builds the browser client assets into `public/static/` (which Vite copies to
 * `dist/` verbatim):
 *
 *   1. `static/js/app.js`      – esbuild bundle of `src/client/**` (IIFE, no CDN)
 *   2. `static/tailwind.css`   – Tailwind compiled at build time (no CDN)
 *   3. `static/vendor/fontawesome/**` – self-hosted icons so offline still works
 *   4. `static/fonts/**` + `static/fonts.css` – self-hosted Sora & Manrope
 *
 * Deterministic, dependency-light and fast (< 2s). Run via `npm run build:client`
 * which is chained into both `npm run dev` and `npm run build`.
 */
import { build } from 'esbuild'
import { cp, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const dev = process.argv.includes('--dev')
const staticDir = path.join(root, 'public', 'static')

/** fail loudly – a silent failure here would ship a broken app shell */
process.on('unhandledRejection', (error) => {
  console.error('\n✖ client build failed:', error)
  process.exit(1)
})

async function exists(p) {
  try {
    await stat(p)
    return true
  } catch {
    return false
  }
}

async function buildClientJs() {
  const outfile = path.join(staticDir, 'js', 'app.js')
  await mkdir(path.dirname(outfile), { recursive: true })
  await build({
    entryPoints: [path.join(root, 'src', 'client', 'main.js')],
    outfile,
    bundle: true,
    format: 'iife',
    target: ['es2020'],
    platform: 'browser',
    minify: !dev,
    legalComments: 'none',
    logLevel: 'warning',
    banner: { js: '/* Command Center client bundle — generated by scripts/build-client.mjs. Edit src/client/** instead. */' },
  })
  const { size } = await stat(outfile)
  return { outfile, size }
}

function buildTailwind() {
  const outfile = path.join(staticDir, 'tailwind.css')
  const cli = require.resolve('tailwindcss/lib/cli.js')
  const args = [cli, '-i', path.join(root, 'src', 'client', 'styles', 'tailwind.css'), '-o', outfile]
  if (!dev) args.push('--minify')
  const result = spawnSync(process.execPath, args, { cwd: root, stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8' })
  if (result.status !== 0) {
    throw new Error(`tailwindcss exited with ${result.status}\n${result.stdout || ''}${result.stderr || ''}`)
  }
  return { outfile }
}

async function buildFontAwesome() {
  const from = path.dirname(require.resolve('@fortawesome/fontawesome-free/package.json'))
  const to = path.join(staticDir, 'vendor', 'fontawesome')
  await rm(to, { recursive: true, force: true })
  await mkdir(path.join(to, 'css'), { recursive: true })
  await cp(path.join(from, 'css', 'all.min.css'), path.join(to, 'css', 'all.min.css'))
  await cp(path.join(from, 'webfonts'), path.join(to, 'webfonts'), { recursive: true })
  // Font Awesome ships .ttf + .woff next to .woff2; modern browsers only need
  // the latter, so drop the heavier legacy formats to keep the shell small.
  for (const file of ['fa-brands-400.ttf', 'fa-regular-400.ttf', 'fa-solid-900.ttf', 'fa-v4compatibility.ttf', 'fa-brands-400.woff', 'fa-regular-400.woff', 'fa-solid-900.woff', 'fa-v4compatibility.woff']) {
    await rm(path.join(to, 'webfonts', file), { force: true })
  }
  let css = await readFile(path.join(to, 'css', 'all.min.css'), 'utf8')
  // Drop the @font-face src entries that point at the removed legacy formats so
  // the CSS never references a file that is not shipped.
  css = css.replace(/,url\([^)]*\.(?:ttf|woff)\)(?:\s*format\([^)]*\))?/g, '')
  if (/\.(?:ttf|woff)\)/.test(css)) {
    throw new Error('Font Awesome CSS still references removed font files — check the rewrite rule.')
  }
  await writeFile(path.join(to, 'css', 'all.min.css'), css)
  return { to }
}

/**
 * Self-hosts Sora + Manrope (latin subset) so the app needs no third party
 * font CDN: identical typography online and offline.
 */
async function buildFonts() {
  const faces = []
  const families = [
    { name: 'Sora', pkg: '@fontsource/sora', weights: [400, 600, 700, 800] },
    { name: 'Manrope', pkg: '@fontsource/manrope', weights: [400, 500, 600, 700, 800] },
  ]
  const to = path.join(staticDir, 'fonts')
  await rm(to, { recursive: true, force: true })
  await mkdir(to, { recursive: true })
  let bytes = 0
  let files = 0
  for (const family of families) {
    const from = path.join(path.dirname(require.resolve(`${family.pkg}/package.json`)), 'files')
    for (const weight of family.weights) {
      const source = path.join(from, `${family.name.toLowerCase()}-latin-${weight}-normal.woff2`)
      const target = path.join(to, `${family.name.toLowerCase()}-latin-${weight}.woff2`)
      await cp(source, target)
      bytes += (await stat(target)).size
      files += 1
      faces.push(`@font-face{font-family:'${family.name}';font-style:normal;font-weight:${weight};font-display:swap;src:url('/static/fonts/${path.basename(target)}') format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;}`)
    }
  }
  await writeFile(path.join(staticDir, 'fonts.css'), `${faces.join('\n')}\n`)
  return { to, files, bytes }
}

const js = await buildClientJs()
const css = buildTailwind()
const fa = await buildFontAwesome()
const fonts = await buildFonts()

const kb = (n) => `${(n / 1024).toFixed(1)} kB`
const tailwindSize = (await stat(css.outfile)).size
const version = (await readFile(path.join(root, 'src', 'shell.ts'), 'utf8')).match(/APP_VERSION\s*=\s*'([^']+)'/)?.[1] ?? '0.0.0'

console.log(`✔ client built (v${version}${dev ? ', dev' : ''})`)
console.log(`  static/js/app.js            ${kb(js.size)}`)
console.log(`  static/tailwind.css         ${kb(tailwindSize)}`)
console.log(`  static/vendor/fontawesome   ${(await exists(fa.to)) ? 'copied' : 'missing'}`)
console.log(`  static/fonts                ${fonts.files} files (${kb(fonts.bytes)}), latin subset only`)
